In [12]:
import numpy as np
#cov= (sum from k=1 to N) [(x^k-mean)^T * (x^k-mean)]/ N-1
#Thus cov[i][j]= sum k-> 1 to N (x^k[i]-mean[i])*(x^k[j]-mean[j])
#Hence, By running 3 loops we can calculate cov matrix
def covmat(data):
  num_features=data.shape[1] #get Number of features
  num_sample=len(data)  #get Number of samples
  cov_matrix = np.zeros((num_features, num_features)) #create cov matrix
  mean=np.sum(data,axis=0)/num_sample #mean for all collumns
  for i in range (num_features):
    for j in range (num_features):
      cov=0;
      for k in range (num_sample): #for each sample take sum
        cov+=((data[k,i]-mean[i])*(data[k,j]-mean[j]))/(num_sample-1)
        cov_matrix[i,j]=cov
  return cov_matrix
#
#
# example dataset
data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# calculating matrix using np.cov function to c
covariance = np.cov(data, rowvar=False)
print("Built-in Covariance Matrix:")
print(covariance)
#using manual function
cov=covmat(data)
print("Manual Covariance Matrix")
print(cov)

Built-in Covariance Matrix:
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
Manual Covariance Matrix
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
