In [15]:
import numpy as np
import sklearn as sk
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split  #inbuilt data split tool

def euclidian(x_test,x_train,y_train):
  num_sample=x_train.shape[0] #number of training samples

  unique_classes, class_counts = np.unique(y_train, return_counts=True) #returns all unique classes with their counts
  class_mean = []#to store mean of all classes
  for n,c in enumerate(unique_classes):
    class_indices = np.where(y_train == c)[0] #returns list of all indices of class c
    class_data = x_train[class_indices] #get all train data of class c
    mean = np.mean(class_data, axis=0) #find mean of that class
    class_mean.append(mean)

  predicted=[] #to store predicted classes
  #To store predictions
  for test_sample in x_test:
    a=[] #to store all distances
    for u in class_mean:
      diff=test_sample-u #(x-meani)
      dist=np.sqrt(np.dot(diff,diff.T)) #||(x-meani)||
      a.append(dist)
    predicted_class=np.argmin(a)
    predicted.append(predicted_class)
  return predicted

def test_train_split(data,target,split_perc):
  perm=np.random.permutation(len(data)) #to get random permutation of 0 to len-1
  x_shuff=data[perm]    #obtain shuffled data
  y_shuff=target[perm]    #obtain shuffled targets
  #get the index till which data is in train set
  n=round((((100-split_perc)*0.01))*len(data)) #round is used to round off to the nearest integer
  x_train=x_shuff[:n] #take starting n elements of shuffled data
  y_train=y_shuff[:n]
  x_test=x_shuff[n:] #take remaining elements of shuffled data
  y_test=y_shuff[n:]
  return x_train, y_train, x_test, y_test

# irisData = load_iris()

# # Create feature and target arrays
# X = irisData.data
# y = irisData.target

# # Split into training and test set
# X_train, X_test, y_train, y_test = train_test_split(
#              X, y, test_size = 0.2, random_state=15)
iris=load_iris()
x_train,y_train,x_test,y_test=test_train_split(iris.data,iris.target,20)
predicted=euclidian(x_test, x_train, y_train)
print(predicted)

#Analysis of this result using 3 class confusion matrix
print("Analysing our model.")

def calculate_confusion_matrix(y_true, y_pred, num_classes):
  # Initialize the confusion matrix of size(nXn) where n=number of classes
  conf_matrix = np.zeros((num_classes, num_classes))
  # Iterate over each sample to create confusion matrix with respect to A
  #.     A.   B.   C.   Predicted
  #.  A  TP   FN   FN
  #   B  FP   TN   TN
  #   C  FP   TN   TN
  for true_class, pred_class in zip(y_true, y_pred):
    #Update the corresponding cell in the confusion matrix
    conf_matrix[int(true_class), int(pred_class)] += 1
  return conf_matrix
def calculate_metrics(conf_matrix):
  #Calculating true positives, false positives, false negatives for each class
  TP = np.diag(conf_matrix)  #obtained as a matrix of order 1xn
  FP = np.sum(conf_matrix, axis=0) - TP   #sum of column-TP
  FN = np.sum(conf_matrix, axis=1) - TP   #sum of row -TP
  # calculating true negatives for each class
  TN = np.sum(conf_matrix) - (TP + FP + FN) #remaining part

  # calculating accuracy for each class
  accuracy = (TP + TN) / np.sum(conf_matrix)

  # calculating precision for each class
  precision = TP / (TP + FP)

  # calculating recall for each class
  recall = TP / (TP + FN)

  # calculating F1 score for each class
  f1_score = 2 * (precision * recall) / (precision + recall)

  return accuracy, precision, recall, f1_score


conf_matrix=calculate_confusion_matrix(y_test,predicted,3)
accuracy, precision, recall, f1_score = calculate_metrics(conf_matrix)
print(conf_matrix)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

[1, 2, 2, 0, 0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
Analysing our model.
[[17.  0.  0.]
 [ 0.  4.  1.]
 [ 0.  1.  7.]]
Accuracy: [1.         0.93333333 0.93333333]
Precision: [1.    0.8   0.875]
Recall: [1.    0.8   0.875]
F1 Score: [1.    0.8   0.875]
