In [ ]:
import numpy as np
import sklearn as sk
from sklearn.datasets import load_iris
iris=load_iris()
#
#taking input of target values and data and the %division between training and test
def test_train_split(data,target,split_perc):
  perm=np.random.permutation(len(data)) #to get random permutation of 0 to len-1
  x_shuff=data[perm]    #obtain shuffled data
  y_shuff=target[perm]    #obtain shuffled targets
  #get the index till which data is in train set
  n=round((((100-split_perc)*0.01))*len(data)) #round is used to round off to the nearest integer
  x_train=x_shuff[:n] #take starting n elements of shuffled data
  y_train=y_shuff[:n]
  x_test=x_shuff[n:] #take remaining elements of shuffled data
  y_test=y_shuff[n:]
  return x_train, y_train, x_test, y_test
#
#
iris=load_iris()
x_train,y_train,x_test,y_test=test_train_split(iris.data,iris.target,20)
print(x_train)

[[5.4 3.7 1.5 0.2]
 [6.8 3.2 5.9 2.3]
 [4.6 3.4 1.4 0.3]
 [5.1 3.7 1.5 0.4]
 [6.4 2.7 5.3 1.9]
 [5.8 2.7 5.1 1.9]
 [5.3 3.7 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [5.5 2.5 4.  1.3]
 [5.6 2.8 4.9 2. ]
 [4.7 3.2 1.3 0.2]
 [6.3 2.9 5.6 1.8]
 [5.  3.4 1.6 0.4]
 [6.5 3.  5.2 2. ]
 [5.  2.3 3.3 1. ]
 [5.4 3.4 1.7 0.2]
 [4.9 3.6 1.4 0.1]
 [5.8 2.7 3.9 1.2]
 [6.1 2.9 4.7 1.4]
 [6.3 2.7 4.9 1.8]
 [6.4 3.2 5.3 2.3]
 [6.3 3.4 5.6 2.4]
 [6.6 3.  4.4 1.4]
 [6.4 3.1 5.5 1.8]
 [4.8 3.1 1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [6.1 2.8 4.  1.3]
 [7.2 3.  5.8 1.6]
 [6.4 2.9 4.3 1.3]
 [6.8 2.8 4.8 1.4]
 [6.5 2.8 4.6 1.5]
 [4.4 2.9 1.4 0.2]
 [6.3 2.5 4.9 1.5]
 [4.9 2.4 3.3 1. ]
 [6.7 3.1 4.4 1.4]
 [6.2 3.4 5.4 2.3]
 [5.8 2.6 4.  1.2]
 [7.6 3.  6.6 2.1]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [4.8 3.4 1.9 0.2]
 [5.6 2.7 4.2 1.3]
 [5.1 3.8 1.5 0.3]
 [5.7 2.8 4.1 1.3]
 [5.7 2.9 4.2 1.3]
 [6.2 2.2 4.5 1.5]
 [6.7 3.1 4.7 1.5]
 [5.9 3.  4.2 1.5]
 [6.2 2.8 4.8 1.8]
 [5.8 2.8 5.1 2.4]
 [6.  2.9 4.